name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: install dependencies
      run: npm ci
    - name: linting
      run: npm run lint

  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['12', '14', '16']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: npm ci
    - name: test
      run: npm test

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: install dependencies
      run: npm install --no-shrinkwrap
    - name: test
      run: npm test
