name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: pnpm
    - name: install dependencies
      run: pnpm install
    - name: linting
      run: pnpm run lint

  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['20', '22', '24']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: pnpm
    - name: install dependencies
      run: pnpm install
    - name: test
      run: pnpm test

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: install dependencies
      run: pnpm install --no-lockfile
    - name: test
      run: pnpm test
